name: music_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  just_audio: ^0.10.4
  audio_metadata_reader: ^1.4.2
  share_plus: ^11.1.0
  http: ^1.2.2
  chewie: ^1.12.1
  chewie_audio: ^1.5.0
  flutter_subtitle: ^0.0.6
  card_swiper: ^3.0.1
  get_storage:
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  provider: ^6.0.5
  video_player: ^2.10.0
  dio: ^5.9.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
